### PR TITLE
Fix for calling update multiple times

### LINKED ISSUE #31: Update mutation fails after first execution
After installing the plain json-graphql-server module and attempting to run the example, I'm seeing an issue with mutations. It seems that the first time we perform any mutation for an entity by id it's successful, but any time we attempt to perform the mutation for the same entity with the sam id again it is unsuccessful. It returns `null` and doesn't update the the value in the database.

Steps to recreate:

1. Copy the file from the example in the docs into db.js [https://github.com/marmelab/json-graphql-server#example](https://github.com/marmelab/json-graphql-server#example)
```javascript
module.exports = {
    posts: [
        { id: 1, title: "Lorem Ipsum", views: 254, user_id: 123 },
        { id: 2, title: "Sic Dolor amet", views: 65, user_id: 456 },
    ],
    users: [
        { id: 123, name: "John Doe" },
        { id: 456, name: "Jane Doe" }
    ],
    comments: [
        { id: 987, post_id: 1, body: "Consectetur adipiscing elit", date: new Date('2017-07-03') },
        { id: 995, post_id: 1, body: "Nam molestie pellentesque dui", date: new Date('2017-08-17') }
    ]
}
```

2. Start the server: `json-graphql-server db.js`

3. Execute a mutation against a post - Should succeed and return the appropriate value
```graphql
mutation {
  updatePost(id:"1", title:"Foo bar", views: 200, user_id:"123") {
    id
  }
}
# returns: 
#{
#  "data": {
#    "updatePost": {
#      "id": "2"
#    }
#  }
#}
```

4. Attempt the exact same mutation again
```graphql
mutation {
  updatePost(id:"1", title:"Foo bar", views: 200, user_id:"123") {
    id
  }
}
# returns: 
#{
#  "data": {
#    "updatePost": null
#  }
#}
```

Thanks!

### PR DESCRIPTION
**Pull request by sioked**
Fixes #31 

There's inconsistencies in the type of the id that's being stored in memory. It looks like after parsing the data file it stores ids as integers in memory, but when we perform an update that update occurs as a string. Avoiding major changes, this always compares ids as integers so we don't need to worry about the inconsistencies.

### CODE REVIEW

File: src/resolver/Mutation/update.js [hunk 1]
```diff
@@ -1,6 +1,8 @@
 export default (entityData = []) => (_, params) => {
     const parsedId = parseInt(params.id, 10); // FIXME fails for non-integer ids
-    const indexOfEntity = entityData.findIndex(e => e.id === parsedId);
+    const indexOfEntity = entityData.findIndex(
+        e => parseInt(e.id, 10) === parsedId
```
Comment (fzaninotto) [inline src/resolver/Mutation/update.js]: But Ids aren't always integers...

Comment (djhi) [reply src/resolver/Mutation/update.js]: Yes, but currently it's not working for non integers ids anyway

Comment (fzaninotto) [reply src/resolver/Mutation/update.js]: Gotcha
